version: '2'
services:
  tanabata:
    container_name: tanabata
    env_file: ./envs/local.env
    build:
      context: .
      dockerfile: Dockerfile
    command: sh run.sh
    volumes:
      - .:/tanabata
      - /dev/shm:/dev/shm
